// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy03UUuyXoJjsjetfVnTitkxPWdgTvwTQ',
    appId: '1:97704373330:web:b6c748b45c3aa0f066438b',
    messagingSenderId: '97704373330',
    projectId: 'mho-shop',
    authDomain: 'mho-shop.firebaseapp.com',
    storageBucket: 'mho-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-GSG5YEtE5p-hL70fTMHChT0B2NtiwU',
    appId: '1:97704373330:android:c8a26d2eaa75856266438b',
    messagingSenderId: '97704373330',
    projectId: 'mho-shop',
    storageBucket: 'mho-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx7aySMmMhhRz0juLGCro8uuuRNfECQZ4',
    appId: '1:97704373330:ios:c58933a5d9ed6a2266438b',
    messagingSenderId: '97704373330',
    projectId: 'mho-shop',
    storageBucket: 'mho-shop.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy03UUuyXoJjsjetfVnTitkxPWdgTvwTQ',
    appId: '1:97704373330:web:33553399f54a941f66438b',
    messagingSenderId: '97704373330',
    projectId: 'mho-shop',
    authDomain: 'mho-shop.firebaseapp.com',
    storageBucket: 'mho-shop.firebasestorage.app',
  );
}
